version: '3.8'
services:
  gmall-coupon:
    image: zhengpanone/jdk8:latest
    container_name: gmall-coupon
    ports:
      - "9010:9010"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    command:  -java -Xms512M -Xmx512M  -jar -Duser.timezone=GMT+08 /testProject/testProject-1.0.0.jar --spring.config.location=/testProject/config/application.yml
  # https://cloud.tencent.com/developer/article/1623549
  mysql:
    image: mysql:8.0.21
    container_name: gmall-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "3306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # root管理员用户密码
      entrypoint:
        sh -c "
          echo 'CREATE DATABASE IF NOT EXISTS gmall_sms; CREATE DATABASE IF NOT EXISTS gmall_ums;' > /docker-entrypoint-initdb.d/init.sql;
          /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
      volumes:
        - ./mysql:/var/lib/mysql

