spring:
  application:
    name: gmall-member
  cloud:
    nacos:
      discovery: # 服务发现
        server-addr: 127.0.0.1:8848
        enabled: true
        namespace: 09aaec5b-628d-43cd-9831-4bfde6df2926
        group: gmall
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/gmall_ums?serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /member
  port: 9020