spring:
  application:
    name: gmall-coupon # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true # 是否启用nacos作为服务注册发现
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall_sms?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9010
  servlet:
    context-path: /coupon
