spring:
  application:
    name: gmall-sys
  profiles:
    active: dev
  boot:
    admin:
      client:
        # Spring Boot Admin Server 地址   http://localhost:8080  可自定义
        url: http://localhost:8080
# 默认情况下，大多数端点都不通过http公开，我们公开了所有端点。对于生产，您应该仔细选择要公开的端点。
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  servlet:
    context-path: /gmall-sys
  port: 9000

